### ISSUE TITLE
能不能把api编译成dll文件跟.so文件，方便其他语言调用

### ISSUE THREAD

**Issue by mengpengfei** [lc-soft/darknetlib#1]
能不能把api编译成dll文件跟.so文件，方便其他语言调用

**Comment by lc-soft** [comment]
能啊，参考 https://github.com/AlexeyAB/darknet 里的 Makefile 文件加点文件就可以了。

**Comment by mengpengfei** [comment]
大佬，我不是用c++编程，对c++不太懂，大佬能编译下吗，十分感谢

**Comment by lc-soft** [comment]
这是 C，不是 C++。只是改个 Makefile 配置，很简单的，你花几十分钟稍微研究下就能搞定。
