### ISSUE TITLE
darknet 版本号不对

### ISSUE THREAD

**Issue by luoxz-ai** [lc-soft/darknetlib#2]
darknet @ 06232b3
您好， 我用这个版本， 发现api 不匹配， 使用最新版本的 darknet 也不正确？
请给出详细的 darknet  commit id,  或给出完整darknet 代码的版本， 谢谢

**Comment by lc-soft** [comment]
贴上报错信息呗

**Comment by luoxz-ai** [comment]
您好， 您用的哪个版本的  darknet ？  但可以肯定不是 darknet @ 06232b3

**Comment by lc-soft** [comment]
嗯，可能是之前推错版本了，我解决一下

**Comment by luoxz-ai** [comment]
好的， 非常感谢

**Comment by lc-soft** [comment]
OK 了
